swagger: "2.0"

info:
  version: "v1.1.0"
  title: "Karbon"
  license:
    name: "Copyright Nutanix Inc. All rights reserved"
  contact:
    email: "karbon-team@nutanix.com"
    name: "Karbon Developers"

tags:
- name: "Cluster"
- name: "Meta"
- name: "Log"

securityDefinitions:
  basicAuth:
    type: basic

definitions:
  error_response:
    type: object
    properties:
      message_info:
        type: object
        description: "{} with the key as the error type and the value as the error message"